#!/bin/bash

if [[ ! -z "${FETCH_CUSTOM_URL}" ]] 
then
    if [ "${FETCH_CUSTOM_URL}" != "NONE" ]
    then
        wget ${FETCH_CUSTOM_URL} -P /opt/karaf/etc
    fi
fi

if [ -f  /opt/karaf/etc/custom_etc.zip ]
then
    unzip -o /opt/karaf/etc/custom_etc.zip -d /opt/karaf/etc
fi

if [[ ! -z "${KARAF_INIT_COMMANDS}" ]]
then
    if [ "${KARAF_INIT_COMMANDS}" != "NONE" ]
    then
        sleep 7 && /opt/karaf/bin/client -r 7  "${KARAF_INIT_COMMANDS}" >> /opt/karaf/data/initcommands.log 2>&1 &
    fi
fi

if [ -f  /opt/karaf/etc/initcommands ]
then
    sleep 7 && /opt/karaf/bin/client -r 7  -f /opt/karaf/etc/initcommands >> /opt/karaf/data/initcommands.log 2>&1  &
fi
